### PR TITLE
Platform Settings

### LINKED ISSUE #85: Number shown where it shouldn't in /management/social-media
There's a number that's shown on /management/social-media, and it shouldnt' be here.

**To Reproduce**
1. Login on an admin account 
2. Got to '/management/social-media'
3. See error

The number shouldn't not appear, and should be removed

### PR DESCRIPTION
**Pull request by alexisljn**
| Q             | A
| ------------- | ---
| Is bugfix?    | No
| New feature?  | Yes
| Fixed issues  | Fixes #85 

Create an area for the admin to manage the platform.

### CODE REVIEW

File: controllers/ProposalController.php [hunk 1]
```diff
@@ -1281,7 +1282,8 @@ public function actionPublishProposal(int $id)
      *
      * @param array $enabledSocialMedia
      * @param SocialMediaPermission $socialMediaPermission
-     * @return |null    */
+     * @return null |null
+     */
```
Comment (EmileCalixte) [inline controllers/ProposalController.php:1286]: 🤔

**Review by EmileCalixte — CHANGES_REQUESTED** [review]
Just a space error to fix and it's good ! 🚀

**Review by EmileCalixte — APPROVED** [review]
